/**
 * Export utilities for GeneMap Discovery
 * Provides PDF-like HTML export, JSON export, and shareable link generation.
 */

/**
 * Export data as a downloadable JSON file
 */
export function exportJSON(data, filename) {
  const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' });
  downloadBlob(blob, `${filename}.json`);
}

/**
 * Export data as a CSV file
 */
export function exportCSV(rows, headers, filename) {
  const csvRows = [
    headers.join(','),
    ...rows.map(row =>
      headers.map(h => {
        const val = row[h] ?? '';
        const escaped = String(val).replace(/"/g, '""');
        return `"${escaped}"`;
      }).join(',')
    ),
  ];
  const blob = new Blob([csvRows.join('\n')], { type: 'text/csv' });
  downloadBlob(blob, `${filename}.csv`);
}

/**
 * Export an analysis report as a printable HTML page (opens print dialog for PDF)
 */
export function exportReport({ title, subtitle, sections, generatedAt }) {
  const html = `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>${escapeHtml(title)} - GeneMap Discovery Report</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; color: #1e293b; padding: 40px; max-width: 800px; margin: 0 auto; }
    .header { border-bottom: 3px solid #4f46e5; padding-bottom: 16px; margin-bottom: 24px; }
    .header h1 { font-size: 24px; color: #1e293b; }
    .header p { font-size: 14px; color: #64748b; margin-top: 4px; }
    .meta { font-size: 12px; color: #94a3b8; margin-top: 8px; }
    .section { margin-bottom: 24px; }
    .section h2 { font-size: 18px; color: #4f46e5; margin-bottom: 12px; border-bottom: 1px solid #e2e8f0; padding-bottom: 6px; }
    .section h3 { font-size: 15px; color: #334155; margin-bottom: 8px; }
    .section p, .section li { font-size: 13px; line-height: 1.6; color: #475569; }
    .section ul { padding-left: 20px; margin-bottom: 12px; }
    table { width: 100%; border-collapse: collapse; margin-bottom: 16px; font-size: 13px; }
    th { background: #f1f5f9; text-align: left; padding: 8px 12px; font-weight: 600; border: 1px solid #e2e8f0; }
    td { padding: 8px 12px; border: 1px solid #e2e8f0; }
    .badge { display: inline-block; padding: 2px 8px; border-radius: 12px; font-size: 11px; font-weight: 600; }
    .badge-blue { background: #dbeafe; color: #1d4ed8; }
    .badge-green { background: #dcfce7; color: #166534; }
    .badge-red { background: #fef2f2; color: #991b1b; }
    .footer { margin-top: 40px; padding-top: 16px; border-top: 1px solid #e2e8f0; font-size: 11px; color: #94a3b8; }
    @media print { body { padding: 20px; } }
  </style>
</head>
<body>
  <div class="header">
    <h1>${escapeHtml(title)}</h1>
    ${subtitle ? `<p>${escapeHtml(subtitle)}</p>` : ''}
    <p class="meta">Generated: ${generatedAt || new Date().toLocaleString()} | GeneMap Discovery</p>
  </div>
  ${sections.map(section => `
  <div class="section">
    <h2>${escapeHtml(section.title)}</h2>
    ${section.content}
  </div>`).join('')}
  <div class="footer">
    <p>This report was generated by GeneMap Discovery. For research purposes only — not a substitute for professional medical advice.</p>
  </div>
</body>
</html>`;

  const win = window.open('', '_blank');
  if (win) {
    win.document.write(html);
    win.document.close();
    setTimeout(() => win.print(), 500);
  }
}

/**
 * Generate a gene card report
 */
export function exportGeneReport(gene) {
  const sections = [];

  sections.push({
    title: 'Gene Overview',
    content: `
      <table>
        <tr><th>Symbol</th><td>${escapeHtml(gene.symbol || '')}</td></tr>
        <tr><th>Full Name</th><td>${escapeHtml(gene.name || gene.fullName || '')}</td></tr>
        <tr><th>Location</th><td>${escapeHtml(gene.chromosome || '')}${gene.location ? ` (${gene.location})` : ''}</td></tr>
        <tr><th>Relevance Score</th><td>${gene.score != null ? gene.score.toFixed(2) : 'N/A'}</td></tr>
        ${gene.omimId ? `<tr><th>OMIM</th><td>${gene.omimId}</td></tr>` : ''}
      </table>
      ${gene.description ? `<p>${escapeHtml(gene.description)}</p>` : ''}
    `,
  });

  if (gene.diseases?.length) {
    sections.push({
      title: 'Associated Diseases',
      content: `<ul>${gene.diseases.map(d => `<li>${escapeHtml(typeof d === 'string' ? d : d.name || d.disease || '')}</li>`).join('')}</ul>`,
    });
  }

  if (gene.phenotypes?.length) {
    sections.push({
      title: 'Associated Phenotypes',
      content: `<ul>${gene.phenotypes.map(p => `<li>${escapeHtml(typeof p === 'string' ? p : p.name || '')}</li>`).join('')}</ul>`,
    });
  }

  if (gene.expressionData?.length) {
    sections.push({
      title: 'Expression Data',
      content: `<table><tr><th>Tissue</th><th>Level</th></tr>${gene.expressionData.slice(0, 15).map(e =>
        `<tr><td>${escapeHtml(e.tissue || e.name || '')}</td><td>${e.value != null ? e.value.toFixed(2) : e.level || 'N/A'}</td></tr>`
      ).join('')}</table>`,
    });
  }

  exportReport({
    title: `Gene Report: ${gene.symbol}`,
    subtitle: gene.name || gene.fullName,
    sections,
  });
}

/**
 * Export a VCF analysis report
 */
export function exportVCFReport(variants, summary) {
  const sections = [
    {
      title: 'Analysis Summary',
      content: `
        <table>
          <tr><th>Total Variants</th><td>${variants.length}</td></tr>
          ${summary?.pathogenicCount != null ? `<tr><th>Pathogenic</th><td><span class="badge badge-red">${summary.pathogenicCount}</span></td></tr>` : ''}
          ${summary?.benignCount != null ? `<tr><th>Benign</th><td><span class="badge badge-green">${summary.benignCount}</span></td></tr>` : ''}
          ${summary?.vusCount != null ? `<tr><th>VUS</th><td><span class="badge badge-blue">${summary.vusCount}</span></td></tr>` : ''}
        </table>
      `,
    },
    {
      title: 'Variant Details',
      content: `<table>
        <tr><th>Gene</th><th>Variant</th><th>Classification</th><th>Frequency</th></tr>
        ${variants.slice(0, 50).map(v => `
          <tr>
            <td>${escapeHtml(v.gene || '')}</td>
            <td>${escapeHtml(v.variant || v.hgvs || `${v.chrom}:${v.pos}`)}</td>
            <td>${escapeHtml(v.classification || v.clinicalSignificance || '')}</td>
            <td>${v.frequency != null ? v.frequency.toFixed(4) : 'N/A'}</td>
          </tr>`
        ).join('')}
      </table>`,
    },
  ];

  exportReport({
    title: 'VCF Analysis Report',
    subtitle: `${variants.length} variants analyzed`,
    sections,
  });
}

/**
 * Copy a shareable text summary to clipboard
 */
export async function copyShareableLink(data, type = 'gene') {
  let text;
  if (type === 'gene') {
    text = `GeneMap Discovery - Gene: ${data.symbol}\nName: ${data.name || data.fullName || ''}\nLocation: ${data.chromosome || ''}${data.location ? ` (${data.location})` : ''}\nScore: ${data.score != null ? data.score.toFixed(2) : 'N/A'}\n${data.diseases?.length ? `Diseases: ${data.diseases.slice(0, 5).map(d => typeof d === 'string' ? d : d.name || '').join(', ')}` : ''}`;
  } else {
    text = `GeneMap Discovery Analysis\n${JSON.stringify(data, null, 2).substring(0, 500)}`;
  }

  try {
    await navigator.clipboard.writeText(text);
    return true;
  } catch {
    return false;
  }
}

// Helpers
function downloadBlob(blob, filename) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  URL.revokeObjectURL(url);
  a.remove();
}

function escapeHtml(str) {
  return String(str)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}
