import React, { useState } from 'react';
import { apiClient } from '@genemap/shared';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Textarea } from '@/components/ui/textarea';
import { Badge } from '@/components/ui/badge';
import { Alert, AlertDescription } from '@/components/ui/alert';
import { Lightbulb, Sparkles, Download, Save, Loader2, AlertCircle } from 'lucide-react';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import { safeModelMarkdownComponents } from '../shared/safeModelMarkdown';

export default function HypothesisGenerator({ studyData, onSave }) {
  const [researchQuestion, setResearchQuestion] = useState('');
  const [hypothesis, setHypothesis] = useState(null);
  const [generating, setGenerating] = useState(false);
  const [error, setError] = useState(null);

  const generateHypothesis = async () => {
    if (!researchQuestion.trim()) {
      setError('Please enter a research question');
      return;
    }

    if (!studyData || studyData.length === 0) {
      setError('No study data available for analysis');
      return;
    }

    setGenerating(true);
    setError(null);

    try {
      const context = {
        researchQuestion,
        studySummary: {
          totalSamples: studyData.length,
          sampleTypes: [...new Set(studyData.map(s => s.sample_type))],
          conditions: [...new Set(studyData.flatMap(s => s.conditions || []))],
          genes: [...new Set(studyData.flatMap(s => s.genes || []))].slice(0, 20),
          dataTypes: [...new Set(studyData.map(s => s.data_type))]
        }
      };

      const result = await apiClient.invokeLlm(
        {
          operation: 'generate_hypothesis',
          researchQuestion: context.researchQuestion,
          studySummary: context.studySummary,
        },
        'research_hypothesis',
      );

      setHypothesis({
        content: result,
        generatedAt: new Date().toISOString(),
        researchQuestion
      });
    } catch (err) {
      console.error('Hypothesis generation failed:', err);
      setError('Failed to generate hypothesis. Please try again.');
    } finally {
      setGenerating(false);
    }
  };

  const handleSave = () => {
    if (hypothesis && onSave) {
      onSave({
        ...hypothesis,
        title: researchQuestion,
        type: 'AI-Generated Hypothesis'
      });
    }
  };

  const handleDownload = () => {
    if (!hypothesis) return;

    const blob = new Blob([
      `# Research Hypothesis\n\n`,
      `**Research Question:** ${hypothesis.researchQuestion}\n\n`,
      `**Generated:** ${new Date(hypothesis.generatedAt).toLocaleString()}\n\n`,
      `---\n\n`,
      hypothesis.content,
      `\n\n---\n\n`,
      `*This hypothesis was generated by GeneMap Discovery AI and should be reviewed and validated by qualified researchers.*`
    ], { type: 'text/markdown' });

    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `hypothesis-${Date.now()}.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <Card>
      <CardHeader>
        <CardTitle className="flex items-center gap-2">
          <Lightbulb className="w-5 h-5 text-yellow-500" />
          AI Hypothesis Generator
        </CardTitle>
        <CardDescription>
          Generate testable research hypotheses based on your study data
        </CardDescription>
      </CardHeader>
      <CardContent className="space-y-4">
        <div>
          <label className="text-sm font-medium mb-2 block">
            Research Question
          </label>
          <Textarea
            placeholder="e.g., How do BRCA1 variants affect treatment response in breast cancer patients?"
            value={researchQuestion}
            onChange={(e) => setResearchQuestion(e.target.value)}
            rows={3}
            className="resize-none"
          />
        </div>

        {studyData && (
          <div className="flex flex-wrap gap-2">
            <Badge variant="outline">
              {studyData.length} samples
            </Badge>
            <Badge variant="outline">
              {[...new Set(studyData.map(s => s.data_type))].length} data types
            </Badge>
            <Badge variant="outline">
              {[...new Set(studyData.flatMap(s => s.genes || []))].length} genes
            </Badge>
          </div>
        )}

        <Button
          onClick={generateHypothesis}
          disabled={generating || !researchQuestion.trim()}
          className="w-full"
        >
          {generating ? (
            <>
              <Loader2 className="w-4 h-4 mr-2 animate-spin" />
              Generating Hypothesis...
            </>
          ) : (
            <>
              <Sparkles className="w-4 h-4 mr-2" />
              Generate Hypothesis
            </>
          )}
        </Button>

        {error && (
          <Alert variant="destructive">
            <AlertCircle className="h-4 w-4" />
            <AlertDescription>{error}</AlertDescription>
          </Alert>
        )}

        {hypothesis && (
          <div className="mt-6 space-y-4">
            <div className="border rounded-lg p-6 bg-gradient-to-br from-yellow-50 to-orange-50">
              <div className="flex items-center gap-2 mb-4">
                <Lightbulb className="w-5 h-5 text-yellow-600" />
                <h3 className="font-semibold text-lg">Generated Hypothesis</h3>
              </div>
              <div className="prose prose-sm max-w-none">
                <ReactMarkdown
                  remarkPlugins={[remarkGfm]}
                  components={safeModelMarkdownComponents}
                >
                  {hypothesis.content}
                </ReactMarkdown>
              </div>
            </div>

            <Alert>
              <AlertCircle className="h-4 w-4" />
              <AlertDescription>
                <strong>Research Tool:</strong> This AI-generated hypothesis is a starting point for investigation. 
                It must be validated through peer review, experimental testing, and consultation with domain experts.
              </AlertDescription>
            </Alert>

            <div className="flex gap-2">
              <Button onClick={handleSave} variant="outline" className="flex-1">
                <Save className="w-4 h-4 mr-2" />
                Save to Study
              </Button>
              <Button onClick={handleDownload} variant="outline" className="flex-1">
                <Download className="w-4 h-4 mr-2" />
                Download
              </Button>
            </div>
          </div>
        )}
      </CardContent>
    </Card>
  );
}